---
version: 1.0.{build}

image:
  - Ubuntu

environment:
  matrix:
    - PYTHON: 2.7
      DOCS: 0
    - PYTHON: 3.6
      DOCS: 1
  API_KEY:
    secure: lXJMVqjukZrKZ16H+Za/mtd7ihJI3tgQKl+D8X0lcno=
  IRC_SERVER:
    secure: g6lhKdOfeE9HvmgZhYRXMw==
  IRC_PORT:
    secure: u9Vi89nx5Lmrv3tnTMq9OA==
  IRC_NICK:
    secure: OVO9f8TnD9Jm8w1g4WaABg==
  IRC_CHANNELS:
    secure: k8v55p1PTJetGc+zIaNMFQ==
  CI: /tmp/ci
  ARTIFACTS: docs/docsite/_build

clone_depth: 50

branches:
  except:
    - devel
    - master

only_commits:
  author: hji@dyntopia.com

matrix:
  fast_finish: true

install:
  - git clone --depth 1 https://github.com/illikainen/ci.git "$CI"
  - ${CI}/utils/ci.sh on_start
  - ${CI}/utils/ci.sh install

artifacts:
  - path: $ARTIFACTS
    name: artifacts

build_script:
  - ${CI}/utils/ci.sh build

test_script:
  - ${CI}/utils/ci.sh test

on_success:
  - ${CI}/utils/ci.sh on_success

on_failure:
  - ${CI}/utils/ci.sh on_failure

on_finish:
  - ${CI}/utils/ci.sh on_finish
