#!/usr/bin/env python3

from src.exceptions import CIError
from src.cli import main
from src.utils import error


if __name__ == "__main__":
    try:
        main()
    except CIError as e:
        error("unhandled CI error: {}", e)
