---
variables:
  DEBIAN_FRONTEND: noninteractive
  CI: /tmp/ci
  CI_PROJECT: $CI_PROJECT_NAME
  CI_DESTDIR: /tmp/build

.apt_template: &apt
  only:
    - /^hji-/
  script: |
    apt-get update
    apt-get install --assume-yes git lsb-release
    git clone --depth 1 https://github.com/illikainen/ci.git "$CI"
    ${CI}/utils/ci.sh on_start
    if ${CI}/utils/ci.sh install build test; then
        ${CI}/utils/ci.sh on_success
    else
        ${CI}/utils/ci.sh on_failure
        exit 1
    fi

test:ubuntu-16.04:
  image: ubuntu:16.04
  <<: *apt

test:ubuntu-latest:
  image: ubuntu:latest
  <<: *apt
