---
variables:
  DOCKER_CONTENT_TRUST: 1

.common_template: &common
  only:
    - /^hji-/
  artifacts:
    paths:
      - t/test-results
    when: on_failure
  script:
    - ${CI_SRC}/ci run-pipeline --notify --trigger

test:alpine-3.11:
  image: ${CI_REGISTRY_IMAGE}/git:alpine-3.11
  <<: *common

test:centos-7:
  image: ${CI_REGISTRY_IMAGE}/git:centos-7
  <<: *common

test:fedora-31:
  image: ${CI_REGISTRY_IMAGE}/git:fedora-31
  <<: *common

test:ubuntu-16.04:
  image: ${CI_REGISTRY_IMAGE}/git:ubuntu-16.04
  <<: *common

test:ubuntu-19.10:
  image: ${CI_REGISTRY_IMAGE}/git:ubuntu-19.10
  <<: *common
