---
variables:
  DEBIAN_FRONTEND: noninteractive
  CI: /tmp/ci
  CI_PROJECT: $CI_PROJECT_NAME
  CI_DESTDIR: /tmp/build
  GIT_TEST_OPTS: --immediate --tee --verbose-log --root=t/test-results

.base_template: &base
  only:
    - /^hji-/
  artifacts:
    paths:
      - t/test-results
    when: on_failure

.apt_template: &apt
  <<: *base
  script: |
    apt-get update
    apt-get install --assume-yes git lsb-release
    git clone --depth 1 https://github.com/illikainen/ci.git "$CI"
    ${CI}/utils/ci.sh on_start
    if ${CI}/utils/ci.sh install build test; then
        ${CI}/utils/ci.sh on_success
        ${CI}/utils/ci.sh on_finish
    else
        ${CI}/utils/ci.sh on_failure
        exit 1
    fi

.dnf_template: &dnf
  <<: *base
  script: |
    dnf install --assumeyes git
    git clone --depth 1 https://github.com/illikainen/ci.git "$CI"
    ${CI}/utils/ci.sh on_start
    if ${CI}/utils/ci.sh install build test; then
        ${CI}/utils/ci.sh on_success
        ${CI}/utils/ci.sh on_finish
    else
        ${CI}/utils/ci.sh on_failure
        exit 1
    fi

test:ubuntu-16.04:
  image: ubuntu:16.04
  variables:
    IRC_EXTRA: ubuntu-16.04
    CI_CAN_START_BUILD: 1
  <<: *apt

test:ubuntu-latest:
  image: ubuntu:latest
  variables:
    IRC_EXTRA: ubuntu-latest
  <<: *apt

test:centos-8:
  image: centos:8
  variables:
    IRC_EXTRA: centos-8
  <<: *dnf

test:fedora-latest:
  image: fedora:latest
  variables:
    IRC_EXTRA: fedora-latest
  <<: *dnf
