---
variables:
  DOCKER_CONTENT_TRUST: 1
  REGISTRY: ${CI_REGISTRY}/${CI_PROJECT_NAMESPACE}/ci/${CI_PROJECT_NAME}

.common:
  only:
    - /^hji-/
  artifacts:
    paths:
      - t/test-results
    when: on_failure
  script:
    - ${CI_SRC}/ci run-pipeline --notify --trigger

test:alpine-3.11:
  image: ${REGISTRY}:alpine-3.11
  extends: .common

test:centos-7:
  image: ${REGISTRY}:centos-7
  extends: .common

test:fedora-31:
  image: ${REGISTRY}:fedora-31
  extends: .common

test:ubuntu-16.04:
  image: ${REGISTRY}:ubuntu-16.04
  extends: .common

test:ubuntu-19.10:
  image: ${REGISTRY}:ubuntu-19.10
  extends: .common
